export interface Transaction {
  id: string
  budgetItemId: string
  amount: number // stored as cents
  date: string // ISO date string YYYY-MM-DD
  note: string | null
  isAutoGenerated: boolean
  recurringItemId: string | null
  createdAt: string
  updatedAt: string
}
