import { pgTable, text, integer, boolean, timestamp } from 'drizzle-orm/pg-core'
import { relations } from 'drizzle-orm'
import { budgetItems } from './budgets'
import { recurringItems } from './recurring'

export const transactions = pgTable('transactions', {
  id: text('id')
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  budgetItemId: text('budget_item_id')
    .notNull()
    .references(() => budgetItems.id, { onDelete: 'cascade' }),
  amount: integer('amount').notNull(), // cents
  date: text('date').notNull(), // YYYY-MM-DD
  note: text('note'),
  isAutoGenerated: boolean('is_auto_generated').notNull().default(false),
  recurringItemId: text('recurring_item_id').references(() => recurringItems.id, {
    onDelete: 'set null',
  }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

export const transactionsRelations = relations(transactions, ({ one }) => ({
  budgetItem: one(budgetItems, {
    fields: [transactions.budgetItemId],
    references: [budgetItems.id],
  }),
  recurringItem: one(recurringItems, {
    fields: [transactions.recurringItemId],
    references: [recurringItems.id],
  }),
}))
