import { and, eq } from 'drizzle-orm'
import { db } from '@/db'
import { budgets, recurringItems, transactions } from '@/db/schema'

export async function applyRecurringToBudget(budgetId: string, userId: string) {
  const budget = await db.query.budgets.findFirst({
    where: and(eq(budgets.id, budgetId), eq(budgets.userId, userId)),
    with: {
      items: {
        with: { transactions: true },
      },
    },
  })

  if (!budget) return null

  const activeRecurring = await db.query.recurringItems.findMany({
    where: and(eq(recurringItems.userId, userId), eq(recurringItems.isActive, true)),
  })

  if (activeRecurring.length === 0) {
    await db
      .update(budgets)
      .set({ recurringApplied: 1 })
      .where(and(eq(budgets.id, budgetId), eq(budgets.userId, userId)))

    return { created: 0 }
  }

  const itemByCategoryId = new Map(budget.items.map((item) => [item.categoryId, item]))
  const existingRecurringIds = new Set(
    budget.items.flatMap((item) =>
      item.transactions
        .map((tx) => tx.recurringItemId)
        .filter((recurringItemId): recurringItemId is string => Boolean(recurringItemId)),
    ),
  )

  const txsToCreate: {
    budgetItemId: string
    amount: number
    date: string
    note: string
    isAutoGenerated: boolean
    recurringItemId: string
  }[] = []

  let matchingRecurringCount = 0
  const maxDay = new Date(budget.year, budget.month, 0).getDate()

  for (const recurring of activeRecurring) {
    const budgetItem = itemByCategoryId.get(recurring.categoryId)
    if (!budgetItem) continue

    matchingRecurringCount += 1
    if (existingRecurringIds.has(recurring.id)) continue

    const day = Math.min(recurring.dayOfMonth, maxDay)
    const date = `${budget.year}-${String(budget.month).padStart(2, '0')}-${String(day).padStart(2, '0')}`

    txsToCreate.push({
      budgetItemId: budgetItem.id,
      amount: recurring.amount,
      date,
      note: recurring.name,
      isAutoGenerated: true,
      recurringItemId: recurring.id,
    })
  }

  if (txsToCreate.length > 0) {
    await db.insert(transactions).values(txsToCreate)
  }

  if (matchingRecurringCount === 0) {
    return {
      created: 0,
      skipped: true,
      reason: 'No matching budget items',
    }
  }

  await db
    .update(budgets)
    .set({ recurringApplied: 1 })
    .where(and(eq(budgets.id, budgetId), eq(budgets.userId, userId)))

  return { created: txsToCreate.length }
}
