import { NextRequest, NextResponse } from 'next/server'
import { eq, and } from 'drizzle-orm'
import { db } from '@/db'
import { budgets, budgetItems, recurringItems, transactions } from '@/db/schema'
import { requireAuth } from '@/middleware/requireAuth'

// POST /api/budgets/:id/apply-recurring
// Applies active recurring items to this budget month, creating auto-generated transactions.
// Idempotent: marks budget.recurringApplied = 1 after first run; subsequent calls are no-ops.
export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const auth = await requireAuth(req)
  if (auth instanceof NextResponse) return auth

  const { id } = await params

  const budget = await db.query.budgets.findFirst({
    where: and(eq(budgets.id, id), eq(budgets.userId, auth.userId)),
    with: {
      items: { with: { category: true } },
    },
  })

  if (!budget) {
    return NextResponse.json({ data: null, error: 'Budget not found' }, { status: 404 })
  }

  if (budget.recurringApplied === 1) {
    return NextResponse.json(
      { data: { skipped: true, reason: 'Already applied' }, error: null },
    )
  }

  const activeRecurring = await db.query.recurringItems.findMany({
    where: and(
      eq(recurringItems.userId, auth.userId),
      eq(recurringItems.isActive, true),
    ),
  })

  if (activeRecurring.length === 0) {
    // Mark as applied even if nothing to do, so we don't re-check every load
    await db.update(budgets).set({ recurringApplied: 1 }).where(eq(budgets.id, id))
    return NextResponse.json({ data: { created: 0 }, error: null })
  }

  // Build a lookup: categoryId → budgetItem for this budget
  const itemByCategoryId = new Map(budget.items.map((i) => [i.categoryId, i]))

  const txsToCreate: {
    budgetItemId: string
    amount: number
    date: string
    note: string
    isAutoGenerated: boolean
    recurringItemId: string
  }[] = []

  for (const recurring of activeRecurring) {
    const budgetItem = itemByCategoryId.get(recurring.categoryId)
    if (!budgetItem) continue // No budget item for this category in this month — skip

    // Pad day to ensure valid date (e.g. day 31 in Feb → clamped using Date)
    const maxDay = new Date(budget.year, budget.month, 0).getDate()
    const day = Math.min(recurring.dayOfMonth, maxDay)
    const date = `${budget.year}-${String(budget.month).padStart(2, '0')}-${String(day).padStart(2, '0')}`

    txsToCreate.push({
      budgetItemId: budgetItem.id,
      amount: recurring.amount,
      date,
      note: recurring.name,
      isAutoGenerated: true,
      recurringItemId: recurring.id,
    })
  }

  if (txsToCreate.length > 0) {
    await db.insert(transactions).values(txsToCreate)
  }

  await db.update(budgets).set({ recurringApplied: 1 }).where(eq(budgets.id, id))

  return NextResponse.json({ data: { created: txsToCreate.length }, error: null })
}
